import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

import { getBlogPosts } from "../utils/blog";

interface HomePageProps {
  articles: any[];
}

const Home: NextPage<HomePageProps> = ({ articles }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        {articles.map((article, index) => (
          <Link
            href={`/blog/${article.slug}`}
            passHref
            key={article.slug || index}
          >
            <a className="block mb-4">{article?.title || ""}</a>
          </Link>
        ))}
      </main>

      <footer></footer>
    </div>
  );
};

export async function getStaticProps() {
  const blogPosts = await getBlogPosts({ skip: 0, take: 0 });
  return {
    props: {
      articles: blogPosts,
    },
  };
}

export default Home;
